### ISSUE TITLE
Обрабатывать транзакции в DB

### ISSUE THREAD

**Issue by zzet** [lenshq/lens_server#21]
Когда начинается транзакция создается Event AR.sql с содержанием "BEGIN", потом может происходить много других вещей и в конце будет событие AR.sql c содержимым "COMMIT". Нужно отлавливать такие ситуации и создавать отдельный Event, который будет говорить о существующей транзакции. Дата начала нового event будет event.started_at у события "BEGIN" а дата конца - event.finished_at у события "COMMIT". Располагаться это событие должно сразу перед событием "BEGIN".

**Comment by vplrt** [comment]
Транзакция может закончится событием ROLLBACK. Этот случай тоже нужно обработать?

**Comment by zzet** [comment]
Да, конечно.

Отправлено с iPhone
