### ISSUE TITLE
Ограничить доступ к приложениям в API

### ISSUE THREAD

**Issue by zzet** [lenshq/lens_server#24]
[Тут](https://github.com/lenshq/lens_server/blob/master/app/controllers/api/v1/applications_controller.rb) предоставляются данные по всем приложениям. Нужно это ограничить в рамках пользователя.

**Comment by zzet** [comment]
@jbmeerkat сделано?

**Comment by jbmeerkat** [comment]
@zzet ты же сам реквест смержил)
закрываю

**Comment by zzet** [comment]
@jbmeerkat я забыл про этот issue
