### ISSUE TITLE
Перенести конфигурацию авторизации через Github в конфиг

### ISSUE THREAD

**Issue by zzet** [lenshq/lens_server#25]

**Comment by vlaew** [comment]
@zzet Избавиться от использования ENV переменных и использовать файлы конфига? Или что имеется в виду?

**Comment by zzet** [comment]
Да, нужно избавиться от переменных окружения и использовать конфиги. Посмотри на https://github.com/zzet/persey . Там можно разделить общий конфиг и приватный.

**Comment by jbmeerkat** [comment]
> Посмотри на https://github.com/zzet/persey 

@zzet @vlaew мне очень не нравятся такие конфиги. Предлагаю просто файл. И что-нибудь [типа такого](https://github.com/railsconfig/config). Умеет все что нужно и не умеет того, что не нужно) что скажете?

**Comment by zzet** [comment]
@jbmeerkat так у нас все будет в yaml файлах. Только часть в shared или домике спрятана, а часть в директории проекта с кодом шариться будет.

**Comment by jbmeerkat** [comment]
@zzet короче я негативно отношусь к конфигам, в которых можно выполнять код. Мы с тобой уже болтали на эту тему =]

**Comment by zzet** [comment]
https://github.com/lenshq/lens_server/commit/34200d3edd8c5ed16af2cd024eb2dd0151ed928a
